### ISSUE TITLE
Missing procedure arguments in Postgresql

### ISSUE THREAD

**Issue by elring** [serge-rider/dbeaver#1081]
In dbeaver version 3.8.1 I can see procedure arguments/parameters/columns in postgresql database (version 9.3 and 9.5), although I only see $1, $2 etc. as parameter name.

In dbeaver 3.8.2 no parameter is shown in procedure detail (in section procedure columns).
Procedure source (DDL) is ok.

Is there some hidden settings or driver parameter to show arguments (with names)?

Thank you.

**Comment by serge-rider** [comment]
This is a bug. And it happens not only with PostgreSQL procedure parameters but with many other "inline" objects too.
Fixed. Probably I'll rebuild 3.8.2 version because this issue is critical..

**Comment by serge-rider** [comment]
Just rebuilt and re-uploaded fixed version. 
Please try fixed version (it is still 3.8.2).

**Comment by elring** [comment]
Wow, that was quick :) 
Now it works like in version 3.8.1. Thank you!

Another problem - I still see procedure parameters with names $1, $2, $3 etc instead of real name. Server supports parameter names since version 9.0 (or something old like that), so this should be no problem. 

Should I file new issue or is it known problem (not yet implemented feature like parameter editing etc)?

**Comment by serge-rider** [comment]
Ok, good. Thanks for report.

Yes, please create another issue for parameter names.
