### ISSUE TITLE
Autocomplete error on mixed case schema.table name (Exasol DB)

### ISSUE THREAD

**Issue by ceesvl** [serge-rider/dbeaver#1157]
When trying in 3.8.3

SELECT BASE. <-autocomplete
FROM "OdsNav"."Service Contract Header" BASE

I get the following error:
java.lang.NullPointerException
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.getTableFromAlias(SQLCompletionAnalyzer.java:363)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionAnalyzer.runAnalyzer(SQLCompletionAnalyzer.java:118)
	at org.jkiss.dbeaver.ui.editors.sql.syntax.SQLCompletionProcessor$ProposalSearchJob.run(SQLCompletionProcessor.java:340)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:103)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

The DB navigator works in getting all the meta data for this table.

Could you check if this an bug or misconfiguration on my side.

Thanks,
Cees

**Comment by serge-rider** [comment]
What is your database?

**Comment by serge-rider** [comment]
Ah, Exasol.
Thanks for report.

**Comment by Sargul** [comment]
Hi Serge,

the structure assistant seems to have some bugs regarding case sensitivity.

I'll look into it tomorrow and I hope I'll be able to fix this ASAP

Regards

Karl

**Comment by serge-rider** [comment]
Ok, thanks,
If this will take much time to fix all bugs then just return empty lists. findObjectsByMask mustn't return null.

**Comment by Sargul** [comment]
I fixed the SQLs in the ExasolStructureAssistant. However autocomplete does not work in this case. Even though the schema (OdsNav) is provided in double quotations the findObjects method is called with casesensitive=false. In my opinion casesensitive should be true.

So auto complete does not work for schemas and object that are case sensitive. I've done the same test with the db2 plugin and auto complete fails there too.

**Comment by serge-rider** [comment]
Yep. There are problems with autocomplete of quoted identifiers (specifically if they have spaces in their names).
I've committed the fix. @Sargul please test

**Comment by Sargul** [comment]
Hi Serge,

still the same problem. The structure assistant still get's called with OdsNav as object mask but caseSensitive method parameter is in false. Tested with both DB2 and Exasol:

DB2:
![db2_error](https://cloud.githubusercontent.com/assets/5595511/22154811/461d8db0-df2d-11e6-8714-6871385151e0.jpg)
Exasol:
![exasol_no_object_found](https://cloud.githubusercontent.com/assets/5595511/22154812/461dbf1a-df2d-11e6-8163-ad30ae6f930f.jpg)

Regards

**Comment by serge-rider** [comment]
In fact structure assistant shouldn't be called in this case at all.
I found another bug in quoted identifiers extraction.

I've have tested described case in DB2 - seems to be working well now.

**Comment by Sargul** [comment]
I've tested with Exasol. Works fine now.

**Comment by serge-rider** [comment]
Great
