### ISSUE TITLE
FIX unable to save UTF-32 characters in Data Grid Editor: SQL Error [1366] [HY000]: Incorrect string value #UTF-8 #java.sql.SQLException #utf32_unicode

### ISSUE THREAD

**Issue by allanlaal** [serge-rider/dbeaver#1320]
connection: MySQL
column charset: utf32_unicode
Connection configuration -> Driver properties -> characterEncoding: UTF-8 (connecting failed with the UTF-32 value)
Connection configuration ->  Result Sets -> Binaries -> String encoding: UTF-8 (also tried with UTF-32)

when saving an UTF-32 character, for example this: 💔
I get this error:
________________________
 SQL Error [1366] [HY000]: Incorrect string value: '\xF0\x9F\x92\x94' for column 'icon' at row 1
  java.sql.SQLException: Incorrect string value: '\xF0\x9F\x92\x94' for column 'icon' at row 1
________________________

P.S. saving the same char with phpMyAdmin works fine

**Comment by serge-rider** [comment]
Not sure I can fix this, looks like MySQL JDBC driver issue.
Can you READ utf-16 string in DBeaver (after you insert them from phpMyAdmin)?

**Comment by allanlaal** [comment]
yes, it displays even all UTF-32 chars correctly, no issues there

**Comment by allanlaal** [comment]
@serge-rider what should I enter into Driver properties -> characterEncoding when I want to use UTF-32 as my connection collation?

**Comment by serge-rider** [comment]
I don't know. This is MySQL driver specific question.

**Comment by allanlaal** [comment]
@serge-rider utf-32 is a valid value for MySQL, but it doesn't work

**Comment by serge-rider** [comment]
This depends on MySQL server version and/or driver version. There are lots of related topics on the net (e.g. http://stackoverflow.com/questions/27374083/how-to-make-mysql-character-set-connection-work-with-utf16).
In any case this doesn't look like a DBeaver issue.

Note: I can't make my local MySQL to work with utf-16. Probably I need to upgrade server or something.

**Comment by allanlaal** [comment]
the same workflow works in phpmyadmin, which is connected to the same server

**Comment by serge-rider** [comment]
Yes, but phpmyadmin doesn't use JDBC driver.

I will make some tests with MySQL 5.7 and the most recent JDBC drivers (6.x+), maybe it is solved there.

**Comment by allanlaal** [comment]
@serge-rider issue persists in 4.2.3, cannot save characters like 💣 (U+1F4A3) in grid editor, which gives error:
Incorrect string value: '\xF0\x9F\x92\xA3' for column 'icon' at row 1
Incorrect string value: '\xF0\x9F\x92\xA3' for column 'icon' at row 1

http://graphemica.com/💣

**Comment by serge-rider** [comment]
This works fine for other databases (PostgreSQL, Oracle, SQL Server).
So this still looks to be MySQL specific (maybe JDBC driver specific). There should be the way to resolve this by connections/server settings.

**Comment by allanlaal** [comment]
my bad, it was a server side issue :)

to fix this, edit/add/update your servers my.cnf to:

	[client]
	default-character-set = utf8mb4

	[mysqld]
	character-set-server = utf8mb4
	collation-server = utf8mb4_unicode_ci

	[mysql]
	default-character-set = utf8mb4

in DBeaver:
Connection configuration -> Driver properties -> characterEncoding: UTF-8
