### ISSUE TITLE
Horizontal scroll bar thickness

### ISSUE THREAD

**Issue by Karsonito** [serge-rider/dbeaver#1570]
When I write the text in the bottom position of the editor, unhiding of the scroll bar is very troublesome.
![screenshot_1](https://cloud.githubusercontent.com/assets/2379481/25000343/99b478dc-2049-11e7-9a61-3d8ac72a5ae3.png)
It hides the text when moving mouse over bar.
Please add ability to disable dynamic thickness.

**Comment by serge-rider** [comment]
This seems be Eclipse/SWT theming issue. I can't fix this but hopefully it'll be fixed in after E4.7 migration (should happen in next couple of months).

**Comment by andywicht** [comment]
Any progress on this issue? I would also really appreciate this possibility.

**Comment by Karsonito** [comment]
@serge-rider 
"This seems be Eclipse/SWT theming issue. I can't fix this but hopefully it'll be fixed in after E4.7 migration"
"DBeaver was migrated to Eclipse 4.8 platform"
is there a way to fix it now?

**Comment by dirkniblick** [comment]
Yeah, this is really obnoxious when you're just trying to edit the last thing you pasted into a script.  Please fix (if possible).

**Comment by abolognino** [comment]
the issue is still present, I don't think this issue should be closed until it's fixed

**Comment by ronniegane** [comment]
I still have this issue. Horizontal scrollbar covers the text area. You can't read anything you're typing on the last line.

Vertical scrollbar also covers the last character of your line.
I'd much prefer if these scrollbars were always visible, if it meant they would be outside the input area.
