### ISSUE TITLE
Make keywords uppercase when typing

### ISSUE THREAD

**Issue by choclin** [serge-rider/dbeaver#295]
In SQLyog, I can start writing a SQL statement and it automatically converts keywords to uppercase within the editior. DBeaver already formats the detected keywords in bold and another color. But uppercase would be really great (as an option) as I like to have the keywords in uppercase, but I am used to not use the shift key :-)

**Comment by choclin** [comment]
Thanks for your quick realization!

I still have a problem that I can reproduce very well:

1. Build DBeaver from source
2. remove ~/.dbeaver to ensure that no old setting can influence the behaviour
3. Start DBeaver
4. create a connection to a MySQL server
5. double click the connection to load a query editor
6. type "select "

When pressing the space bar, I get the following error message on the console. As you can see, I did not change any settings, but used the native ones.

```
2016-03-22 08:29:19.488 - org.eclipse.jface.text.BadLocationException
org.eclipse.jface.text.BadLocationException
	at org.eclipse.jface.text.AbstractDocument.getChar(AbstractDocument.java:806)
	at org.jkiss.dbeaver.ui.editors.sql.indent.SQLAutoIndentStrategy.updateKeywordCase(SQLAutoIndentStrategy.java:155)
	at org.jkiss.dbeaver.ui.editors.sql.indent.SQLAutoIndentStrategy.customizeDocumentCommand(SQLAutoIndentStrategy.java:74)
	at org.eclipse.jface.text.TextViewer.customizeDocumentCommand(TextViewer.java:3779)
	at org.eclipse.jface.text.TextViewer.handleVerifyEvent(TextViewer.java:3816)
	at org.eclipse.jface.text.source.projection.ProjectionViewer.handleVerifyEvent(ProjectionViewer.java:1270)
	at org.eclipse.jface.text.TextViewer$TextVerifyListener.verifyText(TextViewer.java:437)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:273)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1338)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1119)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7276)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8159)
	at org.eclipse.swt.custom.StyledText.doContent(StyledText.java:2502)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:5967)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:5998)
	at org.eclipse.swt.custom.StyledText$7.handleEvent(StyledText.java:5685)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4481)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1329)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1353)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1338)
	at org.eclipse.swt.widgets.Widget.sendIMKeyEvent(Widget.java:1415)
	at org.eclipse.swt.widgets.Control.gtk_commit(Control.java:3100)
	at org.eclipse.swt.widgets.Canvas.gtk_commit(Canvas.java:163)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1961)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5685)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4717)
	at org.eclipse.swt.internal.gtk.OS._gtk_im_context_filter_keypress(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_im_context_filter_keypress(OS.java:8709)
	at org.eclipse.swt.widgets.Control.filterKey(Control.java:2436)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3318)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:793)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1980)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:5685)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4717)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9326)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1225)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2435)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3428)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:694)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:606)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.jkiss.dbeaver.core.application.DBeaverApplication.start(DBeaverApplication.java:110)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

```

**Comment by serge-rider** [comment]
Thanks for info. This happened when keyword was in the very end of SQL text.
Fix committed.

**Comment by choclin** [comment]
Now it works! Is this based on the SQL formatter? When I use the external formatter and setup a formatter that does not make keywords uppercase, I still have these uppercase keywords.

For me, this is okay. But it should be documented well that everyone knows what to expect.

**Comment by serge-rider** [comment]
No, it is not based on formatter. There is a separate config for it:
![keyword-case-config](https://cloud.githubusercontent.com/assets/6398845/13946771/965480fe-f027-11e5-850b-a18adf0e99da.png)

**Comment by javesin** [comment]
In my instance (tried versions 3.6.9 and 3.6.10) the Edit > Format > Format SQL doesn't reflect "Convert keyword case" setting. Could you please verify and fix this?
Thank you.

**Comment by choclin** [comment]
I'm running version 3.6.10 and I can reproduce this.

**Comment by carlosjrcabello** [comment]
This option will adjust when you are typing your statements.

**Comment by serge-rider** [comment]
Please clarify. What exactly function doesn't work? CTRL+ALT-F? Auto-conversion?

**Comment by choclin** [comment]
I meant the auto-conversion, but, I was wrong - sorry. The auto-conversion works.
@javesin Additionally you have to set the keyword case to Upper in General/Editors/SQL Editor/SQL Formatting.

**Comment by serge-rider** [comment]
Ok

**Comment by kirungaj** [comment]
Window >Preferences > Database > SQL Editor > SQL Formatting >Settings Keyword case: Upper 
![Capture](https://user-images.githubusercontent.com/33969902/57432734-f6725800-7236-11e9-9622-81229a54d484.PNG)

**Comment by kirungaj** [comment]
_Window >Preferences > Database > SQL Editor > SQL Formatting >Settings Keyword case: Upper_

![Capture](https://user-images.githubusercontent.com/33969902/57432962-7f898f00-7237-11e9-93be-78fcfad88b1c.PNG)
