### ISSUE TITLE
Cassandra SSL support

### ISSUE THREAD

**Issue by cortopy** [serge-rider/dbeaver#317]
I've set up dbeaver to connect to Cassandra on a remote host. It works OK when client-to-node encryption is not enable. However, when SSL is enabled, dbeaver is unable to connect even though I have checked the SSL option in the connection menu. I get the following error:

```
2016-03-29 16:01:34.746 - org.jkiss.dbeaver.model.exec.DBCException: All host(s) tried for query failed (tried: host/123.456.7.8:9042 (com.datastax.driver.core.exceptions.TransportException: [host/123.456.7.8] Channel has been closed))
org.jkiss.dbeaver.model.exec.DBCException: All host(s) tried for query failed (tried: host/123.456.7.8:9042 (com.datastax.driver.core.exceptions.TransportException: [host/123.456.7.8] Channel has been closed))
    at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.connect(CasExecutionContext.java:54)
    at com.jkiss.dbeaver.ent.cassandra.model.CasDataSource.<init>(CasDataSource.java:102)
    at com.jkiss.dbeaver.ent.cassandra.CasDataSourceProvider.openDataSource(CasDataSourceProvider.java:66)
    at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:597)
    at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:71)
    at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:99)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: host/123.456.7.8:9042 (com.datastax.driver.core.exceptions.TransportException: [host/123.456.7.8] Channel has been closed))
    at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:231)
    at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1382)
    at com.datastax.driver.core.Cluster.init(Cluster.java:162)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:333)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:308)
    at com.datastax.driver.core.Cluster.connect(Cluster.java:250)
    at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.reconnect(CasExecutionContext.java:108)
    at com.jkiss.dbeaver.ent.cassandra.model.CasExecutionContext.connect(CasExecutionContext.java:50)
    ... 6 more
```

I've tried to check if there's anything wrong in the configuration of cassandra server, but I don't think because:
- I'm able to connect in the command line with `cqlsh --ssl`
- dbeaver connects if SSL is disabled in server

Cassandra version: 2.1 (DataStax Enterprise 4.8)
Dbeaver version: 3.6.3

**Comment by Duosnipers** [comment]
I get the exact error message with Dbeaver 3.6.5 when SSL is enabled.
I'm however fine with Dbeaver 3.6.0
Has something changed for Cassandra in the newest versions?

**Comment by serge-rider** [comment]
In fact nothing was changed in Cas connectivity since 3.6.0. Cassandra driver was updated to 3.0.0 in DBeaver 3.6.0 and that's it.
And I can reproduce this problem in both 3.6.0 and 3.6.5.

You need to specify SSL certificates (https://datastax.github.io/java-driver/manual/ssl/).
DBeaver doesn't support special UI for that yet (so you can do it only thru command line parameters). Although SSL configuration UI was added for other databases. 
I think it won't be too complicated to add such UI for Cassandra.

**Comment by dave-hall** [comment]
Just downloaded DBeaver 3.6.10 64 bit - and still having problems with the Cassandra SSL connection.  Now the trust store is gone - and I had that in 3.6.5.  Where did the trust store go to?

**Comment by serge-rider** [comment]
There was no any trust store configuration for Cassandra. At the moment (3.6.10) DBeaver supports SSL config UI only for MySQL and PostgreSQL.

**Comment by dave-hall** [comment]
I stand corrected - I must have been thinking about a different tool like DevCenter by DataStax - my bad and thank you for the correction.  Is there any projected timeline on when Cassandra/SSL will be addressed in DBeaver?

**Comment by serge-rider** [comment]
Probably SSL support will be added right after 3.7 release.
3.7.1-3.7.2.

**Comment by ekskimn** [comment]
@serge-rider Hi Serge, 

I see that this issue is still open but the last comment from you was that it would be added after the 3.7 release.  I am 4.0.5 and I still don't see the feature.  Was wondering if there was an updated timeline on this feature.  Not having it makes using dbeaver a nonstarter for me whcih is too bad because otherwise I have found it great to use (until our cluster went ssl)  =)

**Comment by serge-rider** [comment]
Yep. 
Moving to 4.1 (the next EE release).

**Comment by Magublafix** [comment]
Hi @serge-rider 

Should this be possible when starting Dbeaver with the keystore containing the cassandra ssl certificate?

I tried to add 
-Djavax.net.ssl.trustStore=/path/to/client.truststore
-Djavax.net.ssl.trustStorePassword=password123
to dbeaver.ini
But still I can't open a connection.

regards,
Gerald

**Comment by serge-rider** [comment]
At the moment main problem with this feature is that I don't have Cassandra SSL server in my test environment. Setting it up is more complicated than coding the feature itself.
Hopefully I'll find some time for this.

**Comment by rajani007** [comment]
I have same issue. Please add this feature.

**Comment by ekskimn** [comment]
@serge-rider Hi Serge how is this issue going?  are you blocked?  I would really like to have this issue resolved in 4.1

**Comment by serge-rider** [comment]
Right now I'm blocked by my vacation :)
And yes, I still don't have Cassandra server with enabled SSL in my test env.

**Comment by dantalian-pv** [comment]
I've added next lines into the dbeaver.ini and it works for me on 3.8.5 and 4.0.5 versions:
```
-vmargs
-Djavax.net.ssl.trustStore=/path/to/truststore.jks
-Djavax.net.ssl.trustStorePassword=truststore-password
```
Surprisingly it only works without any quotes (single or double quotes) only. I mean, if put this lines like:
`-Djavax.net.ssl.trustStore="/path/to/truststore.jks"` or `-Djavax.net.ssl.trustStore='/path/to/truststore.jks'` it will not work, because of some reason.

**Comment by serge-rider** [comment]
Cassandra SSL support (in UI) will be added in 4.2:
![default](https://user-images.githubusercontent.com/6398845/28846027-9893d892-7712-11e7-856d-4f81272464df.png)

![default](https://user-images.githubusercontent.com/6398845/28846014-919a3810-7712-11e7-9df5-2811e9fa1bf1.png)

**Comment by p2k** [comment]
It looks nice, but sadly it doesn't work. I bought DBeaver EE 4.2 and setup everything in this dialog, still getting the same error as the issue opener. I've filed a support ticket.
