### ISSUE TITLE
Getting error to open about wrong workspace folder - 3.6.9 (Win x64)

### ISSUE THREAD

**Issue by carlosjrcabello** [serge-rider/dbeaver#495]
Hi there,

This is an oldest bug (3.5+ i think), after install and trying to open it by second time, I got an exception before splash screen. 

Looking up about this error, I realize that Dbeaver didn't create his .dbeaver for my Win user 'Carlos Spohr', instead, his created a folder 'Carlos%Sphor'. See it below:

![image](https://cloud.githubusercontent.com/assets/637767/15660198/3076b068-26af-11e6-984b-4646d14dcb2b.png)

But log file was created at 'Users/Carlos Spohr/.eclipse/', same folder that my Eclipse create his files.
![image](https://cloud.githubusercontent.com/assets/637767/15660221/82f70ca2-26af-11e6-8b7b-77bace04a198.png)

However, here is log about exception talking about permissions that DBeaver doesn't have at 'Program Files' folder.

```
!ENTRY org.eclipse.equinox.preferences 4 2 2016-05-30 21:35:58.223
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.equinox.preferences".
!STACK 0
java.lang.IllegalStateException: The platform metadata area could not be written: C:\Program Files\DBeaver\workspace\.metadata.  By default the platform writes its content
under the current working directory when the platform is launched.  Use the -data parameter to
specify a different content area for the platform.
	at org.eclipse.core.internal.runtime.DataArea.assertLocationInitialized(DataArea.java:61)
	at org.eclipse.core.internal.runtime.DataArea.getStateLocation(DataArea.java:129)
```
Here complete stack:

https://gist.github.com/carlosjrcabello/134c5c5e072c36d9e5322398e80b7392

Is there any mode to change current workspace as Eclipse, or, configure it to create inside User folder in .dbeaver folder ?

**Appendix**

I didn't any customization about system permissions, just default installation folder and checking 'Reset settings' before install. I've reinstalled by four or five times cleaning any residual files or configurations.

**Comment by carlosjrcabello** [comment]
Update,

Using standalone versions (zip) it's OK, but still writes configurations inside .eclipse folder...previously versions was .dbeaver.

**Comment by serge-rider** [comment]
This looks like a conflict with running version of DBeaver. Sometimes Eclipse executable just hangs during shutdown and never finish.
Reboot should solve this problem. Or killing dbeaver.exe in Task Manager (or killall dbeaver).

**Comment by carlosjrcabello** [comment]
Hi there,

So, I did what you said, and I still getting this same error. I'll try to install it in my standalone apps folders to test it.

**Comment by carlosjrcabello** [comment]
OK, installing it in other folder (not Program Files), all seems working normally. I'll continue testing it on next releases to see this occurs again.

If anyone else report an issue like this, I think you can close it.

Thanks Serge.

**Comment by serge-rider** [comment]
I was able to reproduce that.
The problem is in space in the profile name.

**Comment by carlosjrcabello** [comment]
Yep,

DBeaver puts a '%' between words of profile name, at least, on Windows.

On Wed, Jun 1, 2016 at 7:39 AM, Serge Rider <notifications@github.com>
wrote:

> I was able to reproduce that.
> The problem is in space in the profile name.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/495#issuecomment-222956148>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAm7R-833Bepz344MEyFuqJUZanxTzcsks5qHWFigaJpZM4IqGOV>
> .
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by serge-rider** [comment]
Please test EA version
http://dbeaver.jkiss.org/files/ea/

**Comment by carlosjrcabello** [comment]
Worked Serge!

![screen226](https://cloud.githubusercontent.com/assets/637767/15709058/ec680cfc-27d8-11e6-9443-c4a7f352fe8d.png)

DBeaver got correctly user folder and not creating a new one with '%', and I not received an error about workspace permission.

Tested with **dbeaver-ee-3.6.9-x86_64-setup.exe** binary.

**Comment by serge-rider** [comment]
Ok, thanks for testing.
I'll release hotfix version 3.6.10 on the next week.

**Comment by Wismute** [comment]
Quick fix for me was to Start as administrator

Helped when in a hurry and previously working DBeaver somehow stopped opening
