### ISSUE TITLE
SQL statement timeout has no effect on cassandra connection

### ISSUE THREAD

**Issue by WeissGotsman** [serge-rider/dbeaver#850]
![cass](https://cloud.githubusercontent.com/assets/22855561/19411587/2db0be60-9337-11e6-9c2b-8dd986ba4588.png)

The change of "SQL statement timeout" does not affect cassandra connection's default 12s timeout.

1. 
CREATE TABLE IF NOT exists tidata.test1 (
idx int,
tm time,
PRIMARY KEY (idx));

2. just create some random 100 million records

3. do some time costly operation, e.g. 
select COUNT(*) from tidata.test1;

4. result
![cass2](https://cloud.githubusercontent.com/assets/22855561/19411649/22eb508e-9338-11e6-82ab-00d759e2757e.png)

5. how to fix
in the cluster.cpp file of the datastax c++ driver there are 3 functions to change timeouts, the java driver should be similar.

void cass_cluster_set_connect_timeout(CassCluster* cluster,
                                      unsigned timeout_ms) {
  cluster->config().set_connect_timeout(timeout_ms);
}

void cass_cluster_set_request_timeout(CassCluster* cluster,
                                      unsigned timeout_ms) {
  cluster->config().set_request_timeout(timeout_ms);
}

void cass_cluster_set_resolve_timeout(CassCluster* cluster,
                                      unsigned timeout_ms) {
  cluster->config().set_resolve_timeout(timeout_ms);
}

**Comment by serge-rider** [comment]
Yes, statement timeout was just ignored for Cassandra. Will add it in the next version (it is a bit different that in C++ but also quite simple).

**Comment by fabiopedrosa** [comment]
this still isn't solved right?

**Comment by serge-rider** [comment]
It was solved. Statement timeouts can be configured on "SQL Processing" preference page.

**Comment by comdiv** [comment]
It doesn't work - we set 60000 but it still fail after 10sec

**Comment by serge-rider** [comment]
Ah, I see. I thought you wanted to decrease timeout to avoid query hanging.
I'll add use the same statement timeout for statement.read_timeout option in Java driver (this will increase maximum timeout).
Also we'll add extra socket options in the next version - see #2108

Also check http://docs.datastax.com/en/developer/java-driver/3.1/manual/socket_options/ for server-side timeouts configuration.
